### ISSUE TITLE
20180528_RAddicts_datatable.pdf

### ISSUE THREAD

**Issue by Atrebas** [dreamRs/talks#1]
Nice job! Thank you for these slides.
@mattdowle and [data.table](https://github.com/Rdatatable/data.table/wiki) folks are doing an amazing work and it's great to see praise for data.table in the French R community.
As a side remark, there are some typos slide 26: comments for lines 1 and 3 do no match the code and the output of the third command is not correct.
Otherwise, I really like the structure of the talk highlighting the 10 key points and think they were judiciously chosen.

**Comment by mattdowle** [comment]
Completely agree with these sentiments; thanks @sbsdc!  Thanks @pvictor and @mfanny.
I added this talk and links to https://github.com/Rdatatable/data.table/wiki/Presentations.
